## first stage
FROM node:18 AS builder

WORKDIR /frontend/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build-docker-client

## second stage
FROM caddy:latest

ARG CADDYFILE
COPY ./Caddyfile.production /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80

EXPOSE 443
