version: "3"
services:
  react-app:
    image: react-e-commerce-production
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mern-e-commerce
  express-api:
    image: e-commerce-api-production
    restart: unless-stopped
    env_file: ./api/.env
    ports:
      - "8000:8000"
    networks:
      - mern-e-commerce
networks:
  mern-e-commerce:
    driver: bridge

volumes:
  mongo-data:
    driver: local
