version: "3"
services:
  react-app:
    image: react-e-commerce
    restart: unless-stopped
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-e-commerce
  express-api:
    image: e-commerce-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - mern-e-commerce
networks:
  mern-e-commerce:
    driver: bridge

volumes:
  mongo-data:
    driver: local
